//
//  PlacemarksListInterfaces.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PlacemarksListNavigationOption {
}

protocol PlacemarksListWireframeInterface: WireframeInterface {
    func navigate(to option: PlacemarksListNavigationOption)
}

protocol PlacemarksListViewInterface: ViewInterface {
  func refreshPlacemarksTable()
}

protocol PlacemarksListPresenterInterface: PresenterInterface {
  func numberOfPlacemarkSections() -> Int
  func numberOfPlacemarkItems(in section: Int) -> Int
  func placemarkItem(at indexPath: IndexPath) -> PlacemarkCellItem
}

protocol PlacemarksListInteractorInterface: InteractorInterface {
  func getPlacemarks(completion: @escaping ([Placemark]) -> Void)
}
