//
//  PlacemarksListViewController.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlacemarksListViewController: UIViewController {
  
  // MARK: - Public properties -
  
  var presenter: PlacemarksListPresenterInterface!
  
  // MARK: - Lifecycle -
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
}

// MARK: - Extensions -

extension PlacemarksListViewController: PlacemarksListViewInterface {
}

