//
//  PlacemarksListInterfaces.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PlacemarksListNavigationOption {
}

protocol PlacemarksListWireframeInterface: WireframeInterface {
    func navigate(to option: PlacemarksListNavigationOption)
}

protocol PlacemarksListViewInterface: ViewInterface {
}

protocol PlacemarksListPresenterInterface: PresenterInterface {
}

protocol PlacemarksListInteractorInterface: InteractorInterface {
}
