//
//  PlacemarksListPresenter.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlacemarksListPresenter {

    // MARK: - Private properties -

    private unowned var _view: PlacemarksListViewInterface
    private var _interactor: PlacemarksListInteractorInterface
    private var _wireframe: PlacemarksListWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: PlacemarksListWireframeInterface, view: PlacemarksListViewInterface, interactor: PlacemarksListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension PlacemarksListPresenter: PlacemarksListPresenterInterface {
}
