//
//  PlacemarksListInteractor.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PlacemarksListInteractor {
}

// MARK: - Extensions -

extension PlacemarksListInteractor: PlacemarksListInteractorInterface {
}
