//
//  PlacemarksListWireframe.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlacemarksListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: PlacemarksListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = PlacemarksListInteractor()
        let presenter = PlacemarksListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PlacemarksListWireframe: PlacemarksListWireframeInterface {

    func navigate(to option: PlacemarksListNavigationOption) {
    }
}
