//
//  MainPresenter.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/5/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainPresenter {
  
  // MARK: - Private properties -
  
  private unowned var _view: MainViewInterface
  private var _interactor: MainInteractorInterface
  private var _wireframe: MainWireframeInterface
  
  private var _dataStore: PlacemarkPersistenceProtocol!
  
  // MARK: - Lifecycle -
  
  init(wireframe: MainWireframeInterface, view: MainViewInterface, interactor: MainInteractorInterface) {
    _wireframe = wireframe
    _view = view
    _interactor = interactor
    _dataStore = WunderCoreDataStore.shared
  }
  
  func viewDidLoad() {
    getPlacemarks()
  }
}

// MARK: - Extensions -

extension MainPresenter: MainPresenterInterface {
  func getPlacemarks() {
    _view.showProgressHUD()
    _dataStore.deletePlacemarks { [weak self] _ in
      self?._interactor.getPlacemarks { (placemarks) in
        self?._dataStore.createPlacemarks(placemarks) { _ in
          self?._view.hideProgressHUD()
          self?._view.didLoadPlacemarks()
        }
      }
    }
  }
}

