//
//  MainInteractor.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/5/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainInteractor {
}

// MARK: - Extensions -

extension MainInteractor: MainInteractorInterface {
}
