//
//  MainInteractor.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/5/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Alamofire

final class MainInteractor {
  
}

// MARK: - Extensions -

extension MainInteractor: MainInteractorInterface {
  
  func getPlacemarks(completion: @escaping ([Placemark]) -> Void) {
    SessionManager.default.request(Router.getPlacemarks).validate().responseData { response in
      do {
        response.debugLog()
        let decoder = JSONDecoder()
        guard let data = response.data else {
          completion([])
          return
        }
        let placemarks = try decoder.decode(Placemarks.self, from: data)
        completion(placemarks.placemarks)
      } catch {
        debugPrint(error)
      }
    }
  }
  
}
