//
//  MainInterfaces.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/5/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MainNavigationOption {
}

protocol MainWireframeInterface: WireframeInterface {
    func navigate(to option: MainNavigationOption)
}

protocol MainViewInterface: ViewInterface {
}

protocol MainPresenterInterface: PresenterInterface {
}

protocol MainInteractorInterface: InteractorInterface {
}
