//
//  PlacemarksMapInteractor.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PlacemarksMapInteractor {
  private let _placemarksService = PlacemarkDataService(placemarkPersistence: WunderCoreDataStore.shared)
}

// MARK: - Extensions -

extension PlacemarksMapInteractor: PlacemarksMapInteractorInterface {
  func getPlacemarks(completion: @escaping ([Placemark]) -> Void) {
    _placemarksService.fetchPlacemarks { (placemarks) in
      completion(placemarks)
    }
  }
}
