//
//  PlacemarksMapViewController.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlacemarksMapViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: PlacemarksMapPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension PlacemarksMapViewController: PlacemarksMapViewInterface {
}
