//
//  PlacemarksMapInterfaces.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PlacemarksMapNavigationOption {
}

protocol PlacemarksMapWireframeInterface: WireframeInterface {
    func navigate(to option: PlacemarksMapNavigationOption)
}

protocol PlacemarksMapViewInterface: ViewInterface {
}

protocol PlacemarksMapPresenterInterface: PresenterInterface {
}

protocol PlacemarksMapInteractorInterface: InteractorInterface {
}
