//
//  PlacemarksMapPresenter.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlacemarksMapPresenter {

    // MARK: - Private properties -

    private unowned var _view: PlacemarksMapViewInterface
    private var _interactor: PlacemarksMapInteractorInterface
    private var _wireframe: PlacemarksMapWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: PlacemarksMapWireframeInterface, view: PlacemarksMapViewInterface, interactor: PlacemarksMapInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension PlacemarksMapPresenter: PlacemarksMapPresenterInterface {
}
