//
//  PlacemarksMapWireframe.swift
//  WunderTest
//
//  Created by Danijel Kecman on 11/6/18.
//  Copyright (c) 2018 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlacemarksMapWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: PlacemarksMapViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = PlacemarksMapInteractor()
        let presenter = PlacemarksMapPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PlacemarksMapWireframe: PlacemarksMapWireframeInterface {

    func navigate(to option: PlacemarksMapNavigationOption) {
    }
}
